# Generated by Django 5.1.7 on 2025-05-29 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontainer',
            options={},
        ),
        migrations.AlterField(
            model_name='usercontainer',
            name='container_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usercontainer',
            name='container_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usercontainer',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercontainer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='usercontainer',
            table='user_containers',
        ),
    ]
