# Generated by Django 5.2.4 on 2025-09-29 05:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CORSScanSessionTC1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_apis", models.IntegerField(default=0)),
                ("scanned_apis", models.IntegerField(default=0)),
                ("vulnerable_apis", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("info_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cors_scan_sessions",
            },
        ),
        migrations.CreateModel(
            name="CORSScanResultTC1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(db_index=True)),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("api_url", models.URLField(max_length=500)),
                ("api_method", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vulnerable", "Vulnerable"),
                            ("not_vulnerable", "Not Vulnerable"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "access_control_allow_origin",
                    models.TextField(blank=True, null=True),
                ),
                ("access_control_allow_credentials", models.BooleanField(null=True)),
                (
                    "access_control_allow_headers",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "access_control_allow_methods",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "access_control_max_age",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "origin_tested",
                    models.CharField(default="https://evil.example", max_length=255),
                ),
                (
                    "preflight_response_status",
                    models.IntegerField(blank=True, null=True),
                ),
                ("actual_request_status", models.IntegerField(blank=True, null=True)),
                ("vulnerability_description", models.TextField(blank=True)),
                ("exploit_poc", models.TextField(blank=True)),
                ("remediation", models.TextField(blank=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("raw_response_headers", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cors_scan_results",
                "indexes": [
                    models.Index(
                        fields=["scan_id", "status"],
                        name="cors_scan_r_scan_id_9af8ef_idx",
                    ),
                    models.Index(
                        fields=["scan_id", "severity"],
                        name="cors_scan_r_scan_id_11c8c0_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="cors_scan_r_created_4a2aff_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScanTC2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scan_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_apis", models.IntegerField(default=0)),
                ("scanned_apis", models.IntegerField(default=0)),
                ("vulnerabilities_found", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_8_scan_tc2",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanMetricsTC2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_duration_seconds", models.FloatField(default=0.0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("info_count", models.IntegerField(default=0)),
                ("http_only_apis", models.IntegerField(default=0)),
                ("https_only_apis", models.IntegerField(default=0)),
                ("mixed_protocol_apis", models.IntegerField(default=0)),
                ("weak_tls_apis", models.IntegerField(default=0)),
                ("missing_security_headers", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="api_8.scantc2",
                    ),
                ),
            ],
            options={
                "db_table": "api_8_scan_metrics_tc2",
            },
        ),
        migrations.CreateModel(
            name="ScanHistoryTC2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="api_8.scantc2",
                    ),
                ),
            ],
            options={
                "db_table": "api_8_scan_history_tc2",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ScanTC3",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("scan_id", models.IntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_apis", models.IntegerField(default=0)),
                ("scanned_apis", models.IntegerField(default=0)),
                ("vulnerabilities_found", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_8_scan_tc3",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanStatsTC3",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("vulnerabilities_by_severity", models.JSONField(default=dict)),
                ("vulnerabilities_by_type", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="api_8.scantc3",
                    ),
                ),
            ],
            options={
                "db_table": "api_8_scan_stats_tc3",
            },
        ),
        migrations.CreateModel(
            name="ScanHistoryTC3",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("tested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="api_8.scantc3",
                    ),
                ),
            ],
            options={
                "db_table": "api_8_scan_history_tc3",
                "ordering": ["-tested_at"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityTC2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("api_url", models.URLField()),
                ("api_method", models.CharField(max_length=10)),
                (
                    "vulnerability_type",
                    models.CharField(default="TLS/Transport Security", max_length=100),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("fixed", "Fixed"),
                            ("false_positive", "False Positive"),
                            ("accepted_risk", "Accepted Risk"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("supports_http", models.BooleanField(default=False)),
                ("supports_https", models.BooleanField(default=False)),
                ("tls_versions", models.JSONField(default=dict)),
                ("cipher_suites", models.JSONField(default=dict)),
                ("certificate_info", models.JSONField(default=dict)),
                ("security_headers", models.JSONField(default=dict)),
                ("hsts_enabled", models.BooleanField(default=False)),
                ("evidence", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("exploit_details", models.TextField(blank=True)),
                ("ai_analysis", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="api_8.scantc2",
                    ),
                ),
            ],
            options={
                "db_table": "api_8_vulnerability_tc2",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityTC3",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("api_url", models.URLField()),
                ("api_method", models.CharField(max_length=10)),
                (
                    "vulnerability_type",
                    models.CharField(
                        choices=[
                            ("VERBOSE_ERRORS", "Verbose Errors"),
                            ("DEBUG_MODE", "Debug Mode"),
                            ("STACK_TRACES", "Stack Traces"),
                            ("VERSION_DISCLOSURE", "Version Disclosure"),
                            ("FRAMEWORK_EXPOSURE", "Framework Exposure"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("evidence", models.JSONField()),
                ("recommendation", models.TextField()),
                ("cve_references", models.JSONField(default=list)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="api_8.scantc3",
                    ),
                ),
            ],
            options={
                "db_table": "api_8_vulnerability_tc3",
                "ordering": ["-discovered_at"],
            },
        ),
    ]
