# Generated by Django 5.2.4 on 2025-09-16 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("application_name", models.CharField(max_length=255)),
                ("business_logic", models.TextField()),
                (
                    "sensitive_data",
                    models.CharField(
                        choices=[
                            ("none", "No sensitive data"),
                            ("pii", "Personal Identifiable Information (PII)"),
                            ("financial", "Financial Data"),
                            ("health", "Health Data"),
                            ("multiple", "Multiple types of sensitive data"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "third_party_integrations",
                    models.CharField(
                        choices=[
                            ("none", "No third-party integrations"),
                            ("few", "Few (1-3) third-party integrations"),
                            ("many", "Many (4+) third-party integrations"),
                            (
                                "critical",
                                "Critical dependencies on third-party services",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "error_handling",
                    models.CharField(
                        choices=[
                            ("basic", "Basic error handling"),
                            ("advanced", "Advanced error handling with logging"),
                            (
                                "comprehensive",
                                "Comprehensive error handling, logging, and recovery",
                            ),
                            ("minimal", "Minimal or no error handling"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user_input_handling",
                    models.CharField(
                        choices=[
                            ("none", "No file uploads or large data inputs"),
                            ("text_only", "Text inputs only, no file uploads"),
                            ("limited_files", "Limited file uploads with restrictions"),
                            ("extensive_files", "Extensive file upload capabilities"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "architecture",
                    models.CharField(
                        choices=[
                            ("monolith", "Monolithic Architecture"),
                            ("client_server", "Client-Server Architecture"),
                            ("microservices", "Microservices Architecture"),
                            ("serverless", "Serverless Architecture"),
                            ("hybrid", "Hybrid Architecture"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hosting",
                    models.CharField(
                        choices=[
                            ("on_premise", "On-Premise"),
                            ("aws", "Amazon Web Services (AWS)"),
                            ("azure", "Microsoft Azure"),
                            ("gcp", "Google Cloud Platform (GCP)"),
                            ("other_cloud", "Other Cloud Provider"),
                            ("hybrid", "Hybrid (Cloud + On-Premise)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tech_stack", models.TextField()),
                (
                    "platforms",
                    models.CharField(
                        choices=[
                            ("web_only", "Web Application Only"),
                            ("web_mobile", "Web and Mobile Applications"),
                            ("web_desktop", "Web and Desktop Applications"),
                            ("all", "Web, Mobile, and Desktop Applications"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_security",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Security (HTTPS, Simple Encryption)"),
                            ("standard", "Standard Security Practices"),
                            (
                                "advanced",
                                "Advanced Security (End-to-end Encryption, etc.)",
                            ),
                            ("minimal", "Minimal Security Measures"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "legacy_dependencies",
                    models.CharField(
                        choices=[
                            ("none", "No Legacy Dependencies"),
                            ("minor", "Minor Legacy Dependencies"),
                            ("major", "Major Legacy Dependencies"),
                            ("critical", "Critical Legacy Dependencies"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monitoring",
                    models.CharField(
                        choices=[
                            ("comprehensive", "Comprehensive Monitoring and Alerts"),
                            ("standard", "Standard Logging and Monitoring"),
                            ("basic", "Basic Logging Only"),
                            ("minimal", "Minimal or No Monitoring"),
                        ],
                        max_length=20,
                    ),
                ),
                ("application_description", models.TextField(blank=True, null=True)),
                ("risk_score", models.FloatField(default=0.0)),
                (
                    "application_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="risk_assessment.applicationtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
