# Generated by Django 4.2.18 on 2025-03-12 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generator', models.CharField(default='azure', max_length=10)),
                ('attack_name', models.CharField(max_length=255)),
                ('scan_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_app_name', models.CharField(max_length=255)),
                ('azure_model_name', models.CharField(max_length=255)),
                ('azure_deployment_name', models.CharField(max_length=255)),
                ('azure_endpoint_url', models.URLField()),
                ('azure_api_key', models.CharField(max_length=255)),
                ('yaml_file', models.CharField(blank=True, max_length=1024, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAIDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generator', models.CharField(default='openai', max_length=10)),
                ('attack_name', models.CharField(max_length=255)),
                ('scan_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_app_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('yaml_file', models.CharField(blank=True, max_length=1024, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('trigger', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('run_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt_seq', models.IntegerField(blank=True, null=True)),
                ('attempt_idx', models.IntegerField(blank=True, null=True)),
                ('generator', models.CharField(blank=True, max_length=255, null=True)),
                ('probe', models.CharField(blank=True, max_length=255, null=True)),
                ('detector', models.CharField(blank=True, max_length=255, null=True)),
                ('generations_per_prompt', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('azure_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.azuredb')),
                ('openai_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.openaidb')),
            ],
        ),
    ]
