# Generated by Django 4.2.18 on 2025-02-12 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_name', models.CharField(max_length=255)),
                ('probes_name', models.CharField(max_length=500)),
                ('category_matrix', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.TextField()),
                ('goal', models.TextField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('output', models.TextField()),
                ('trigger', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('run_id', models.CharField(blank=True, max_length=512, null=True)),
                ('attempt_id', models.CharField(blank=True, max_length=512, null=True)),
                ('attempt_seq', models.IntegerField(blank=True, null=True)),
                ('attempt_idx', models.IntegerField(blank=True, null=True)),
                ('generator', models.CharField(blank=True, max_length=512, null=True)),
                ('probe', models.CharField(blank=True, max_length=512, null=True)),
                ('detector', models.CharField(blank=True, max_length=512, null=True)),
                ('generations_per_prompt', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAIIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('model_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attack_name', models.TextField(blank=True, null=True)),
                ('probe_lists', models.TextField(blank=True, null=True)),
                ('yaml_name', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AzureDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('azure_model_name', models.CharField(max_length=255)),
                ('azure_endpoint_url', models.URLField()),
                ('azure_deployment_name', models.CharField(max_length=255)),
                ('azure_api_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attack_name', models.TextField(blank=True, null=True)),
                ('probe_lists', models.TextField(blank=True, null=True)),
                ('yaml_name', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
