# Generated by Django 5.2.4 on 2025-09-29 05:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcurrentSessionScanTC6",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scan_id",
                    models.IntegerField(
                        help_text="Reference to api_orch_scan table", unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("login_api_identified", models.BooleanField(default=False)),
                ("login_api_url", models.TextField(blank=True, null=True)),
                (
                    "login_api_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("vulnerability_found", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "api_4_concurrent_session_scan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(unique=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_apis", models.IntegerField(default=0)),
                ("tested_apis", models.IntegerField(default=0)),
                ("vulnerable_apis", models.IntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("logs", models.TextField(blank=True)),
            ],
            options={
                "db_table": "api_4_scan_history",
            },
        ),
        migrations.CreateModel(
            name="ScanStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(unique=True)),
                ("total_tests", models.IntegerField(default=0)),
                ("total_vulnerabilities", models.IntegerField(default=0)),
                ("avg_success_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_4_scan_stats",
            },
        ),
        migrations.CreateModel(
            name="UnboundedPaginationScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.CharField(max_length=255)),
                ("api_url", models.TextField()),
                ("method", models.CharField(default="GET", max_length=10)),
                ("headers", models.JSONField()),
                ("body", models.JSONField(blank=True, null=True)),
                ("query_params", models.JSONField(blank=True, null=True)),
                ("authorization", models.JSONField(blank=True, null=True)),
                ("is_vulnerable", models.BooleanField(default=False)),
                (
                    "vulnerable_parameter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("test_value_used", models.IntegerField(blank=True, null=True)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_size", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("chatgpt_analysis", models.TextField(blank=True, null=True)),
                ("identified_parameters", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "unbounded_pagination_scans",
            },
        ),
        migrations.CreateModel(
            name="AsyncTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("is_success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("request_details", models.JSONField(default=dict)),
                ("response_details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_4_asynctestresults",
                "indexes": [
                    models.Index(
                        fields=["scan_id"], name="api_4_async_scan_id_4ee2b8_idx"
                    ),
                    models.Index(
                        fields=["api_name"], name="api_4_async_api_nam_38e6e2_idx"
                    ),
                    models.Index(
                        fields=["is_success"], name="api_4_async_is_succ_ba28f7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FileDownloadTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField()),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("is_vulnerable", models.BooleanField(default=False)),
                ("success_rate", models.FloatField(default=0.0)),
                ("test_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("details", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "api_4_filedownload_tests",
                "indexes": [
                    models.Index(
                        fields=["scan_id"], name="api_4_filed_scan_id_a2fb57_idx"
                    ),
                    models.Index(
                        fields=["api_id"], name="api_4_filed_api_id_fb2fbb_idx"
                    ),
                    models.Index(
                        fields=["is_vulnerable"], name="api_4_filed_is_vuln_6783aa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FileUploadScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField()),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("api_url", models.URLField(max_length=500)),
                ("api_method", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("vulnerable", "Vulnerable"),
                            ("suspicious", "Suspicious"),
                            ("error", "Error"),
                        ],
                        default="safe",
                        max_length=20,
                    ),
                ),
                (
                    "vulnerability_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("webshell", "Webshell Upload"),
                            ("large_file", "Large File Upload"),
                            ("unrestricted", "Unrestricted File Type"),
                            ("mixed", "Multiple Issues"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("accepts_file_upload", models.BooleanField(default=False)),
                ("webshell_upload_success", models.BooleanField(default=False)),
                ("large_file_upload_success", models.BooleanField(default=False)),
                ("unrestricted_file_types", models.BooleanField(default=False)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                ("response_body_snippet", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("uploaded_files", models.JSONField(blank=True, default=list)),
                ("rejected_files", models.JSONField(blank=True, default=list)),
                ("scan_duration", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "file_upload_scan_results",
                "unique_together": {("scan_id", "api_id")},
            },
        ),
        migrations.CreateModel(
            name="FileUploadTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.BigIntegerField()),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("webshell", "Webshell Upload"),
                            ("large_file", "Large File Upload"),
                            ("unrestricted", "Unrestricted File Type"),
                            ("mixed", "Multiple Issues"),
                        ],
                        max_length=20,
                    ),
                ),
                ("upload_success", models.BooleanField(default=False)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_message", models.TextField(blank=True)),
                ("upload_location", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_tests",
                        to="api_4.fileuploadscanresult",
                    ),
                ),
            ],
            options={
                "db_table": "file_upload_tests",
            },
        ),
        migrations.CreateModel(
            name="RateLimitScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_id",
                    models.IntegerField(help_text="Original scan ID from api_orch"),
                ),
                (
                    "api_id",
                    models.IntegerField(
                        help_text="API ID from api_orch_postmanapi table"
                    ),
                ),
                ("api_name", models.CharField(max_length=255)),
                ("api_url", models.URLField(max_length=1000)),
                ("method", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_vulnerable", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("requests_sent", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("rate_limit_detected", models.BooleanField(default=False)),
                ("rate_limit_threshold", models.IntegerField(blank=True, null=True)),
                (
                    "response_codes",
                    models.JSONField(
                        default=dict, help_text="Distribution of HTTP response codes"
                    ),
                ),
                (
                    "response_times",
                    models.JSONField(
                        default=list, help_text="List of response times in ms"
                    ),
                ),
                (
                    "rate_limit_headers",
                    models.JSONField(
                        default=dict, help_text="Rate limiting headers found"
                    ),
                ),
                ("vulnerability_description", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("scan_started_at", models.DateTimeField(auto_now_add=True)),
                ("scan_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api4_rate_limit_scans",
            },
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("debug", "Debug"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("request_number", models.IntegerField(blank=True, null=True)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Response time in seconds", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="api_4.ratelimitscan",
                    ),
                ),
            ],
            options={
                "db_table": "api4_scan_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ScanLogTC6",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("DEBUG", "Debug"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "step",
                    models.CharField(
                        help_text="Which step of the process", max_length=100
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional data for the log entry",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="api_4.concurrentsessionscantc6",
                    ),
                ),
            ],
            options={
                "db_table": "api_4_scan_log",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(unique=True)),
                ("total_apis", models.IntegerField(default=0)),
                ("completed_apis", models.IntegerField(default=0)),
                ("vulnerable_apis", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scan_sessions",
            },
        ),
        migrations.CreateModel(
            name="TokenTestResultTC6",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_1", models.TextField(help_text="First access token")),
                ("token_2", models.TextField(help_text="Second access token")),
                ("token_1_active_after_5min", models.BooleanField(default=False)),
                ("token_2_active_after_5min", models.BooleanField(default=False)),
                (
                    "test_api_url",
                    models.TextField(help_text="API used for testing token validity"),
                ),
                ("test_api_method", models.CharField(default="GET", max_length=10)),
                ("vulnerability_confirmed", models.BooleanField(default=False)),
                ("token_1_response_code", models.IntegerField(blank=True, null=True)),
                ("token_2_response_code", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_results",
                        to="api_4.concurrentsessionscantc6",
                    ),
                ),
            ],
            options={
                "db_table": "api_4_token_test_result",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityReportTC6",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Concurrent Session Management Vulnerability",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("impact", models.TextField()),
                ("recommendation", models.TextField()),
                (
                    "evidence",
                    models.JSONField(help_text="Evidence of the vulnerability"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerability_report",
                        to="api_4.concurrentsessionscantc6",
                    ),
                ),
            ],
            options={
                "db_table": "api_4_vulnerability_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ratelimitscan",
            index=models.Index(
                fields=["scan_id"], name="api4_rate_l_scan_id_d7d4ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitscan",
            index=models.Index(fields=["status"], name="api4_rate_l_status_5efe60_idx"),
        ),
        migrations.AddIndex(
            model_name="ratelimitscan",
            index=models.Index(
                fields=["is_vulnerable"], name="api4_rate_l_is_vuln_d217e4_idx"
            ),
        ),
    ]
