# Generated by Django 5.2.4 on 2025-09-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.CharField(max_length=255)),
                ("api_id", models.CharField(max_length=255)),
                ("vulnerability_type", models.CharField(max_length=100)),
                ("severity", models.CharField(max_length=50)),
                ("details", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_custom_testing_scanresult",
            },
        ),
    ]
