# Generated by Django 5.2.4 on 2025-09-29 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("client_name", models.CharField(max_length=255)),
                ("client_app_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "postman_collection_file",
                    models.FileField(upload_to="postman_collections/"),
                ),
                (
                    "postman_environment_file",
                    models.FileField(
                        blank=True, null=True, upload_to="postman_environments/"
                    ),
                ),
                (
                    "environment_variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Environment variables from Postman environment file",
                    ),
                ),
                (
                    "test_case_selections",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Selected test cases for this scan",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostmanAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(max_length=2000, null=True)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("body", models.JSONField(blank=True, default=dict)),
                ("authorization", models.JSONField(blank=True, default=dict)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                (
                    "folder_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("pre_request_script", models.TextField(blank=True, null=True)),
                ("test_script", models.TextField(blank=True, null=True)),
                (
                    "original_url",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                ("original_headers", models.JSONField(blank=True, default=dict)),
                ("original_body", models.JSONField(blank=True, default=dict)),
                ("original_query_params", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postman_apis",
                        to="api_orch.scan",
                    ),
                ),
            ],
            options={
                "ordering": ["folder_path", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScanTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_attempt", models.DateTimeField(blank=True, null=True)),
                ("login_successful", models.BooleanField(default=False)),
                ("login_error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="api_orch.scan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestCaseSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_category",
                    models.CharField(
                        choices=[
                            ("API1:2023", "API1:2023"),
                            ("API2:2023", "API2:2023"),
                            ("API3:2023", "API3:2023"),
                            ("API4:2023", "API4:2023"),
                            ("API5:2023", "API5:2023"),
                            ("API6:2023", "API6:2023"),
                            ("API7:2023", "API7:2023"),
                            ("API8:2023", "API8:2023"),
                            ("API9:2023", "API9:2023"),
                            ("Custom Testing", "Custom Testing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "test_case",
                    models.CharField(
                        choices=[
                            (
                                "TC-1: Broken Object Level Authorization",
                                "TC-1: Broken Object Level Authorization",
                            ),
                            (
                                "TC-2: Broken User Authentication",
                                "TC-2: Broken User Authentication",
                            ),
                            (
                                "TC-3: Excessive Data Exposure",
                                "TC-3: Excessive Data Exposure",
                            ),
                            (
                                "TC-4: Lack of Resources & Rate Limiting",
                                "TC-4: Lack of Resources & Rate Limiting",
                            ),
                            (
                                "TC-5: Broken Function Level Authorization",
                                "TC-5: Broken Function Level Authorization",
                            ),
                            ("TC-6: Mass Assignment", "TC-6: Mass Assignment"),
                            (
                                "TC-7: Security Misconfiguration",
                                "TC-7: Security Misconfiguration",
                            ),
                            (
                                "TC-1: Broken Authentication",
                                "TC-1: Broken Authentication",
                            ),
                            (
                                "TC-2: Unrestricted Resource Consumption",
                                "TC-2: Unrestricted Resource Consumption",
                            ),
                            (
                                "TC-3: Broken Object Property Level Authorization",
                                "TC-3: Broken Object Property Level Authorization",
                            ),
                            (
                                "TC-4: Unrestricted Access to Sensitive Business Flows",
                                "TC-4: Unrestricted Access to Sensitive Business Flows",
                            ),
                            (
                                "TC-5: Server Side Request Forgery",
                                "TC-5: Server Side Request Forgery",
                            ),
                            (
                                "TC-6: Security Misconfiguration",
                                "TC-6: Security Misconfiguration",
                            ),
                            (
                                "TC-7: Improper Inventory Management",
                                "TC-7: Improper Inventory Management",
                            ),
                            ("TC-1: Unlisted Endpoints", "TC-1: Unlisted Endpoints"),
                            (
                                "TC-2: Access Staging/Dev Environments",
                                "TC-2: Access Staging/Dev Environments",
                            ),
                            (
                                "TC-3: API Documentation Exposure",
                                "TC-3: API Documentation Exposure",
                            ),
                            ("TC-4: Verb Tunneling", "TC-4: Verb Tunneling"),
                            (
                                "TC-5: Version Enumeration of APIs",
                                "TC-5: Version Enumeration of APIs",
                            ),
                            (
                                "TC-6: Monitoring/Health Endpoints",
                                "TC-6: Monitoring/Health Endpoints",
                            ),
                            ("TC-7: Admin APIs", "TC-7: Admin APIs"),
                            (
                                "TC-1: Custom Security Test Case 1",
                                "TC-1: Custom Security Test Case 1",
                            ),
                            (
                                "TC-2: Custom Security Test Case 2",
                                "TC-2: Custom Security Test Case 2",
                            ),
                            (
                                "TC-3: Custom Security Test Case 3",
                                "TC-3: Custom Security Test Case 3",
                            ),
                            (
                                "TC-4: Custom Security Test Case 4",
                                "TC-4: Custom Security Test Case 4",
                            ),
                            (
                                "TC-5: Custom Security Test Case 5",
                                "TC-5: Custom Security Test Case 5",
                            ),
                            (
                                "TC-6: Custom Security Test Case 6",
                                "TC-6: Custom Security Test Case 6",
                            ),
                            (
                                "TC-7: Custom Security Test Case 7",
                                "TC-7: Custom Security Test Case 7",
                            ),
                        ],
                        max_length=60,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["api_category", "test_case"],
                "unique_together": {("api_category", "test_case")},
            },
        ),
    ]
