# Generated by Django 5.2.4 on 2025-11-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_orch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="total_llm_analyzed",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="total_ssrf_candidates",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
