# Generated by Django 5.2.4 on 2025-09-25 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanResultTC5",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("api_url", models.URLField()),
                ("api_method", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vulnerable", "Vulnerable"),
                            ("secure", "Secure"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("evidence", models.JSONField(default=dict)),
                ("risk_score", models.FloatField(default=0.0)),
                ("payload_used", models.JSONField(default=dict)),
                ("response_analysis", models.JSONField(default=dict)),
                ("exploit_details", models.TextField(blank=True, null=True)),
                ("remediation_suggestion", models.TextField(blank=True, null=True)),
                ("false_positive", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_2_scan_result",
                "ordering": ["-risk_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanTC5",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("scan_id", models.IntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_apis", models.IntegerField(default=0)),
                ("scanned_apis", models.IntegerField(default=0)),
                ("vulnerabilities_found", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_2_scan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCredentialTC2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("password", models.CharField(max_length=255)),
                ("credential_type", models.CharField(default="common", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_2_test_credentials",
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityTemplateTC3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("vulnerability_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("impact", models.TextField()),
                ("recommendation", models.TextField()),
                ("test_payloads", models.JSONField(default=list)),
                ("detection_patterns", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api2_vulnerability_templates",
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityTypeTC5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("remediation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_2_vulnerability_type",
            },
        ),
        migrations.CreateModel(
            name="JWTScanTC4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_apis", models.IntegerField(default=0)),
                ("scanned_apis", models.IntegerField(default=0)),
                ("vulnerable_apis", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("scan_duration", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "jwt_scan_tc4",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JWTScanLogTC4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("debug", "Debug"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("api_id", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("additional_data", models.JSONField(default=dict)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="api_2.jwtscantc4",
                    ),
                ),
            ],
            options={
                "db_table": "jwt_scan_log_tc4",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="JWTScanConfigTC4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_none_algorithm", models.BooleanField(default=True)),
                ("test_weak_secrets", models.BooleanField(default=True)),
                ("test_algorithm_confusion", models.BooleanField(default=True)),
                ("test_payload_manipulation", models.BooleanField(default=True)),
                ("test_expired_tokens", models.BooleanField(default=True)),
                ("test_malformed_tokens", models.BooleanField(default=True)),
                ("role_escalation_payloads", models.JSONField(default=list)),
                ("custom_payloads", models.JSONField(default=list)),
                ("weak_secrets", models.JSONField(default=list)),
                ("request_timeout", models.IntegerField(default=30)),
                ("max_retries", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="api_2.jwtscantc4",
                    ),
                ),
            ],
            options={
                "db_table": "jwt_scan_config_tc4",
            },
        ),
        migrations.CreateModel(
            name="JWTTokenAnalysisTC4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField()),
                ("original_token", models.TextField()),
                ("token_header", models.JSONField(default=dict)),
                ("token_payload", models.JSONField(default=dict)),
                ("token_signature", models.TextField(blank=True, null=True)),
                ("algorithm", models.CharField(blank=True, max_length=20, null=True)),
                ("issuer", models.CharField(blank=True, max_length=255, null=True)),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                ("ai_risk_assessment", models.TextField(blank=True, null=True)),
                ("ai_recommendations", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_analyses",
                        to="api_2.jwtscantc4",
                    ),
                ),
            ],
            options={
                "db_table": "jwt_token_analysis_tc4",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiRequestTC5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_url", models.URLField()),
                ("request_method", models.CharField(max_length=10)),
                ("request_headers", models.JSONField(default=dict)),
                ("request_body", models.TextField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(default=dict)),
                ("response_body", models.TextField(blank=True, null=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="api_2.scanresulttc5",
                    ),
                ),
            ],
            options={
                "db_table": "api_2_api_request",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ScanSessionTC1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(db_index=True, unique=True)),
                ("total_apis", models.IntegerField(default=0)),
                ("completed_apis", models.IntegerField(default=0)),
                ("failed_apis", models.IntegerField(default=0)),
                ("vulnerabilities_found", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scanning", "Scanning"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("scan_config", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api2_scan_sessions",
            },
        ),
        migrations.CreateModel(
            name="ScanSessionTC3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_apis", models.IntegerField(default=0)),
                ("apis_scanned", models.IntegerField(default=0)),
                ("vulnerabilities_found", models.IntegerField(default=0)),
                ("scan_config", models.JSONField(default=dict)),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("info_count", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api2_scan_sessions_tc3",
            },
        ),
        migrations.AddField(
            model_name="scanresulttc5",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="api_2.scantc5",
            ),
        ),
        migrations.CreateModel(
            name="ScanLogTC5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="api_2.scantc5",
                    ),
                ),
            ],
            options={
                "db_table": "api_2_scan_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilitySummaryTC1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(db_index=True)),
                ("vulnerability_type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=20)),
                ("count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api2_vulnerability_summary",
                "unique_together": {("scan_id", "vulnerability_type", "severity")},
            },
        ),
        migrations.AddField(
            model_name="scanresulttc5",
            name="vulnerability_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api_2.vulnerabilitytypetc5",
            ),
        ),
        migrations.CreateModel(
            name="ScanConfigurationTC5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("max_concurrent_requests", models.IntegerField(default=5)),
                ("request_timeout", models.IntegerField(default=30)),
                ("retry_attempts", models.IntegerField(default=3)),
                ("delay_between_requests", models.FloatField(default=1.0)),
                ("use_ai_analysis", models.BooleanField(default=True)),
                ("ai_model", models.CharField(default="gpt-3.5-turbo", max_length=50)),
                ("custom_payloads", models.JSONField(default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enabled_vulnerability_types",
                    models.ManyToManyField(to="api_2.vulnerabilitytypetc5"),
                ),
            ],
            options={
                "db_table": "api_2_scan_configuration",
            },
        ),
        migrations.CreateModel(
            name="JWTVulnerabilityTC4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("api_url", models.URLField()),
                ("api_method", models.CharField(max_length=10)),
                (
                    "vulnerability_type",
                    models.CharField(
                        choices=[
                            ("none_algorithm", "None Algorithm"),
                            ("weak_secret", "Weak Secret"),
                            ("algorithm_confusion", "Algorithm Confusion"),
                            ("payload_manipulation", "Payload Manipulation"),
                            ("expired_token_accepted", "Expired Token Accepted"),
                            ("malformed_token_accepted", "Malformed Token Accepted"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_vulnerable", models.BooleanField(default=False)),
                ("original_token", models.TextField(blank=True, null=True)),
                ("forged_token", models.TextField(blank=True, null=True)),
                ("original_response_code", models.IntegerField(blank=True, null=True)),
                ("forged_response_code", models.IntegerField(blank=True, null=True)),
                ("original_response_body", models.TextField(blank=True, null=True)),
                ("forged_response_body", models.TextField(blank=True, null=True)),
                ("payload_changes", models.JSONField(default=dict)),
                ("exploitation_details", models.TextField(blank=True, null=True)),
                ("ai_analysis", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="api_2.jwtscantc4",
                    ),
                ),
            ],
            options={
                "db_table": "jwt_vulnerability_tc4",
                "ordering": ["-created_at"],
                "unique_together": {("scan", "api_id", "vulnerability_type")},
            },
        ),
        migrations.CreateModel(
            name="ScanResultTC1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(db_index=True)),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=500)),
                ("api_method", models.CharField(max_length=10)),
                ("api_url", models.TextField()),
                (
                    "vulnerability_type",
                    models.CharField(
                        choices=[
                            ("weak_auth", "Missing or Weak Authentication"),
                            ("broken_access", "Broken Access Control"),
                            ("injection", "Injection Vulnerability"),
                            ("data_exposure", "Data Exposure"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scanning", "Scanning"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("impact", models.TextField()),
                ("recommendation", models.TextField()),
                ("request_sent", models.TextField(blank=True, null=True)),
                ("response_received", models.TextField(blank=True, null=True)),
                ("evidence", models.TextField(blank=True, null=True)),
                ("scan_started_at", models.DateTimeField(auto_now_add=True)),
                ("scan_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api2_scan_results",
                "indexes": [
                    models.Index(
                        fields=["scan_id", "status"],
                        name="api2_scan_r_scan_id_d5203f_idx",
                    ),
                    models.Index(
                        fields=["vulnerability_type", "severity"],
                        name="api2_scan_r_vulnera_0b29da_idx",
                    ),
                    models.Index(
                        fields=["created_by", "scan_started_at"],
                        name="api2_scan_r_created_d3a0dd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScanResultTC2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField()),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("api_url", models.TextField()),
                ("api_method", models.CharField(max_length=10)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("vulnerability_found", models.BooleanField(default=False)),
                (
                    "vulnerability_type",
                    models.CharField(
                        default="Credential Stuffing / Brute Force", max_length=100
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("total_attempts", models.IntegerField(default=0)),
                ("successful_attempts", models.IntegerField(default=0)),
                ("failed_attempts", models.IntegerField(default=0)),
                ("rate_limited_attempts", models.IntegerField(default=0)),
                ("avg_response_time", models.FloatField(blank=True, null=True)),
                ("status_codes_found", models.JSONField(default=dict)),
                ("rate_limiting_detected", models.BooleanField(default=False)),
                ("account_lockout_detected", models.BooleanField(default=False)),
                ("captcha_detected", models.BooleanField(default=False)),
                ("exploit_successful", models.BooleanField(default=False)),
                ("exploit_details", models.TextField(blank=True, null=True)),
                ("recommendations", models.TextField(blank=True, null=True)),
                ("test_credentials_used", models.JSONField(default=list)),
                ("response_samples", models.JSONField(default=list)),
                ("error_messages", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_2_scan_results",
                "indexes": [
                    models.Index(
                        fields=["scan_id"], name="api_2_scan__scan_id_4cdd31_idx"
                    ),
                    models.Index(
                        fields=["scan_status"], name="api_2_scan__scan_st_b0a085_idx"
                    ),
                    models.Index(
                        fields=["vulnerability_found"],
                        name="api_2_scan__vulnera_1c8c19_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="api_2_scan__created_6b433c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScanResultTC3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField()),
                ("api_id", models.IntegerField()),
                (
                    "vulnerability_type",
                    models.CharField(
                        choices=[
                            ("weak_password_policy", "Weak or Default Password Policy"),
                            ("sql_injection", "SQL Injection"),
                            ("xss", "Cross-Site Scripting"),
                            ("csrf", "Cross-Site Request Forgery"),
                            ("auth_bypass", "Authentication Bypass"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("api_name", models.CharField(max_length=255)),
                ("api_method", models.CharField(max_length=10)),
                ("api_url", models.TextField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("impact", models.TextField()),
                ("recommendation", models.TextField()),
                ("test_payload", models.JSONField(default=dict)),
                ("test_response", models.JSONField(default=dict)),
                ("exploit_successful", models.BooleanField(default=False)),
                ("evidence", models.JSONField(default=dict)),
                ("screenshots", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api2_scan_results_tc3",
                "indexes": [
                    models.Index(
                        fields=["scan_id"], name="api2_scan_r_scan_id_87b42e_idx"
                    ),
                    models.Index(
                        fields=["vulnerability_type"],
                        name="api2_scan_r_vulnera_3cef57_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="api2_scan_r_severit_908157_idx"
                    ),
                    models.Index(
                        fields=["status"], name="api2_scan_r_status_76662f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="api2_scan_r_created_6bfc22_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScanSummaryTC2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.IntegerField(unique=True)),
                ("total_apis", models.IntegerField(default=0)),
                ("completed_apis", models.IntegerField(default=0)),
                ("pending_apis", models.IntegerField(default=0)),
                ("failed_apis", models.IntegerField(default=0)),
                ("total_vulnerabilities", models.IntegerField(default=0)),
                ("critical_vulnerabilities", models.IntegerField(default=0)),
                ("high_vulnerabilities", models.IntegerField(default=0)),
                ("medium_vulnerabilities", models.IntegerField(default=0)),
                ("low_vulnerabilities", models.IntegerField(default=0)),
                ("scan_status", models.CharField(default="pending", max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_scan_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_2_scan_summaries",
                "indexes": [
                    models.Index(
                        fields=["scan_id"], name="api_2_scan__scan_id_d0ad86_idx"
                    ),
                    models.Index(
                        fields=["scan_status"], name="api_2_scan__scan_st_e8e1d5_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="api_2_scan__created_ecea30_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="scanresulttc5",
            index=models.Index(
                fields=["scan", "status"], name="api_2_scan__scan_id_7b6e62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanresulttc5",
            index=models.Index(
                fields=["vulnerability_type", "status"],
                name="api_2_scan__vulnera_adf78f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scanresulttc5",
            index=models.Index(
                fields=["risk_score"], name="api_2_scan__risk_sc_78969a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanresulttc5",
            index=models.Index(fields=["api_id"], name="api_2_scan__api_id_1c1132_idx"),
        ),
    ]
