# Generated by Django 5.2.4 on 2026-02-13 10:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecurityAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "architecture_diagram",
                    models.FileField(upload_to="architecture_diagrams/"),
                ),
                ("application_purpose", models.TextField(blank=True, null=True)),
                ("business_objectives", models.TextField(blank=True, null=True)),
                (
                    "business_criticality",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("impact_of_failure", models.TextField(blank=True, null=True)),
                (
                    "supported_business_processes",
                    models.TextField(blank=True, null=True),
                ),
                ("data_sensitivity", models.TextField(blank=True, null=True)),
                ("data_classification_levels", models.TextField(blank=True, null=True)),
                ("regulatory_requirements", models.TextField(blank=True, null=True)),
                ("compliance_requirements", models.TextField(blank=True, null=True)),
                ("stakeholders", models.TextField(blank=True, null=True)),
                ("system_owners", models.TextField(blank=True, null=True)),
                ("risk_tolerance", models.TextField(blank=True, null=True)),
                ("risk_acceptance_criteria", models.TextField(blank=True, null=True)),
                (
                    "application_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("usage_model", models.TextField(blank=True, null=True)),
                ("functional_overview", models.TextField(blank=True, null=True)),
                ("major_modules", models.TextField(blank=True, null=True)),
                ("user_roles", models.TextField(blank=True, null=True)),
                ("access_types", models.TextField(blank=True, null=True)),
                ("expected_traffic", models.TextField(blank=True, null=True)),
                ("load_patterns", models.TextField(blank=True, null=True)),
                (
                    "deployment_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "high_level_architecture",
                    models.FileField(
                        blank=True, null=True, upload_to="architecture_files/"
                    ),
                ),
                (
                    "logical_architecture",
                    models.FileField(
                        blank=True, null=True, upload_to="architecture_files/"
                    ),
                ),
                (
                    "physical_architecture",
                    models.FileField(
                        blank=True, null=True, upload_to="architecture_files/"
                    ),
                ),
                (
                    "data_flow_diagrams",
                    models.FileField(
                        blank=True, null=True, upload_to="architecture_files/"
                    ),
                ),
                ("trust_boundaries", models.TextField(blank=True, null=True)),
                ("component_interaction", models.TextField(blank=True, null=True)),
                ("design_patterns", models.TextField(blank=True, null=True)),
                ("programming_languages", models.TextField(blank=True, null=True)),
                ("frameworks_versions", models.TextField(blank=True, null=True)),
                ("libraries_packages", models.TextField(blank=True, null=True)),
                ("runtime_environments", models.TextField(blank=True, null=True)),
                ("databases", models.TextField(blank=True, null=True)),
                ("storage_systems", models.TextField(blank=True, null=True)),
                ("middleware_components", models.TextField(blank=True, null=True)),
                ("message_queues", models.TextField(blank=True, null=True)),
                ("api_gateways", models.TextField(blank=True, null=True)),
                ("web_servers", models.TextField(blank=True, null=True)),
                ("application_servers", models.TextField(blank=True, null=True)),
                ("containerization_platforms", models.TextField(blank=True, null=True)),
                ("orchestration_platforms", models.TextField(blank=True, null=True)),
                (
                    "hosting_environment",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cloud_services", models.TextField(blank=True, null=True)),
                ("network_architecture", models.TextField(blank=True, null=True)),
                ("network_topology", models.TextField(blank=True, null=True)),
                ("network_segmentation", models.TextField(blank=True, null=True)),
                ("subnets", models.TextField(blank=True, null=True)),
                ("load_balancers", models.TextField(blank=True, null=True)),
                ("traffic_routing", models.TextField(blank=True, null=True)),
                ("firewall_config", models.TextField(blank=True, null=True)),
                ("waf_config", models.TextField(blank=True, null=True)),
                ("cdn_usage", models.TextField(blank=True, null=True)),
                ("regions", models.TextField(blank=True, null=True)),
                ("availability_zones", models.TextField(blank=True, null=True)),
                ("high_availability_design", models.TextField(blank=True, null=True)),
                ("backup_architecture", models.TextField(blank=True, null=True)),
                ("disaster_recovery_setup", models.TextField(blank=True, null=True)),
                ("authentication_mechanisms", models.TextField(blank=True, null=True)),
                ("authorization_model", models.TextField(blank=True, null=True)),
                ("sso_federation", models.TextField(blank=True, null=True)),
                ("mfa_enforcement", models.TextField(blank=True, null=True)),
                ("service_authentication", models.TextField(blank=True, null=True)),
                ("secrets_management", models.TextField(blank=True, null=True)),
                ("key_management", models.TextField(blank=True, null=True)),
                ("privileged_access_controls", models.TextField(blank=True, null=True)),
                ("account_provisioning", models.TextField(blank=True, null=True)),
                ("account_deprovisioning", models.TextField(blank=True, null=True)),
                ("data_types_processed", models.TextField(blank=True, null=True)),
                ("data_types_stored", models.TextField(blank=True, null=True)),
                ("sensitive_data_locations", models.TextField(blank=True, null=True)),
                ("data_flow_paths", models.TextField(blank=True, null=True)),
                ("encryption_at_rest", models.TextField(blank=True, null=True)),
                ("encryption_in_transit", models.TextField(blank=True, null=True)),
                ("key_rotation_practices", models.TextField(blank=True, null=True)),
                ("data_retention_policies", models.TextField(blank=True, null=True)),
                ("data_masking", models.TextField(blank=True, null=True)),
                ("data_tokenization", models.TextField(blank=True, null=True)),
                ("sensitive_data_in_logs", models.TextField(blank=True, null=True)),
                ("data_import_paths", models.TextField(blank=True, null=True)),
                ("data_export_paths", models.TextField(blank=True, null=True)),
                ("third_party_integrations", models.TextField(blank=True, null=True)),
                ("external_dependencies", models.TextField(blank=True, null=True)),
                ("internal_apis", models.TextField(blank=True, null=True)),
                ("external_apis", models.TextField(blank=True, null=True)),
                ("partner_integrations", models.TextField(blank=True, null=True)),
                ("vendor_integrations", models.TextField(blank=True, null=True)),
                ("webhooks", models.TextField(blank=True, null=True)),
                ("callbacks", models.TextField(blank=True, null=True)),
                ("file_transfer_interfaces", models.TextField(blank=True, null=True)),
                ("api_authentication", models.TextField(blank=True, null=True)),
                ("rate_limiting", models.TextField(blank=True, null=True)),
                ("input_validation_controls", models.TextField(blank=True, null=True)),
                ("secure_coding_standards", models.TextField(blank=True, null=True)),
                ("threat_modeling_status", models.TextField(blank=True, null=True)),
                ("security_design_reviews", models.TextField(blank=True, null=True)),
                ("output_encoding_controls", models.TextField(blank=True, null=True)),
                ("error_handling_approach", models.TextField(blank=True, null=True)),
                ("session_management", models.TextField(blank=True, null=True)),
                ("injection_protections", models.TextField(blank=True, null=True)),
                ("xss_protections", models.TextField(blank=True, null=True)),
                ("dependency_scanning", models.TextField(blank=True, null=True)),
                ("container_scanning", models.TextField(blank=True, null=True)),
                ("image_scanning", models.TextField(blank=True, null=True)),
                ("runtime_security_controls", models.TextField(blank=True, null=True)),
                ("network_protocols", models.TextField(blank=True, null=True)),
                ("open_ports", models.TextField(blank=True, null=True)),
                ("exposed_services", models.TextField(blank=True, null=True)),
                ("tls_configuration", models.TextField(blank=True, null=True)),
                ("certificate_management", models.TextField(blank=True, null=True)),
                ("internal_external_exposure", models.TextField(blank=True, null=True)),
                ("zero_trust_controls", models.TextField(blank=True, null=True)),
                ("service_mesh_controls", models.TextField(blank=True, null=True)),
                ("sdlc_methodology", models.TextField(blank=True, null=True)),
                ("code_review_requirements", models.TextField(blank=True, null=True)),
                ("static_analysis_tooling", models.TextField(blank=True, null=True)),
                ("dynamic_testing_tooling", models.TextField(blank=True, null=True)),
                ("sca_tooling", models.TextField(blank=True, null=True)),
                ("cicd_pipeline_design", models.TextField(blank=True, null=True)),
                ("build_artifact_controls", models.TextField(blank=True, null=True)),
                ("environment_separation", models.TextField(blank=True, null=True)),
                ("secrets_handling_pipelines", models.TextField(blank=True, null=True)),
                ("logging_architecture", models.TextField(blank=True, null=True)),
                ("security_event_logging", models.TextField(blank=True, null=True)),
                ("centralized_log_collection", models.TextField(blank=True, null=True)),
                ("siem_integration", models.TextField(blank=True, null=True)),
                ("alerting_rules", models.TextField(blank=True, null=True)),
                ("detection_rules", models.TextField(blank=True, null=True)),
                ("monitoring_coverage", models.TextField(blank=True, null=True)),
                ("audit_trail", models.TextField(blank=True, null=True)),
                ("log_retention_periods", models.TextField(blank=True, null=True)),
                ("patch_management", models.TextField(blank=True, null=True)),
                ("configuration_management", models.TextField(blank=True, null=True)),
                ("change_management", models.TextField(blank=True, null=True)),
                (
                    "incident_response_procedures",
                    models.TextField(blank=True, null=True),
                ),
                ("operational_runbooks", models.TextField(blank=True, null=True)),
                ("support_maintenance_model", models.TextField(blank=True, null=True)),
                ("fault_tolerance_mechanisms", models.TextField(blank=True, null=True)),
                ("redundancy_design", models.TextField(blank=True, null=True)),
                ("auto_scaling_config", models.TextField(blank=True, null=True)),
                ("retry_logic", models.TextField(blank=True, null=True)),
                ("circuit_breaker_logic", models.TextField(blank=True, null=True)),
                ("backup_restore_testing", models.TextField(blank=True, null=True)),
                ("rto_targets", models.TextField(blank=True, null=True)),
                ("rpo_targets", models.TextField(blank=True, null=True)),
                ("third_party_services", models.TextField(blank=True, null=True)),
                ("vendor_risk_assessments", models.TextField(blank=True, null=True)),
                ("open_source_components", models.TextField(blank=True, null=True)),
                ("license_risks", models.TextField(blank=True, null=True)),
                ("dependency_update_cadence", models.TextField(blank=True, null=True)),
                ("component_support_status", models.TextField(blank=True, null=True)),
                ("compliance_standards", models.TextField(blank=True, null=True)),
                ("control_framework_mappings", models.TextField(blank=True, null=True)),
                ("prior_audit_findings", models.TextField(blank=True, null=True)),
                ("policy_exceptions", models.TextField(blank=True, null=True)),
                ("existing_risk_register", models.TextField(blank=True, null=True)),
                ("known_vulnerabilities", models.TextField(blank=True, null=True)),
                ("accepted_risks", models.TextField(blank=True, null=True)),
                ("architecture_assumptions", models.TextField(blank=True, null=True)),
                ("design_constraints", models.TextField(blank=True, null=True)),
                ("technical_debt_areas", models.TextField(blank=True, null=True)),
                (
                    "overall_risk_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("risk_reasoning", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "security_assessments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="security_as_status_4c8a41_idx",
                    ),
                    models.Index(
                        fields=["overall_risk_score"],
                        name="security_as_overall_d8547a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VulnerableComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("control_title", models.CharField(max_length=255)),
                (
                    "control_description",
                    models.TextField(
                        help_text="Should start with 'It was observed...'"
                    ),
                ),
                (
                    "control_impact",
                    models.TextField(help_text="Describe what happens if exploited"),
                ),
                (
                    "control_recommendation",
                    models.TextField(
                        help_text="Should start with 'It is recommended...'"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("informational", "Informational"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("fixed", "Fixed"),
                            ("accepted", "Accepted"),
                            ("false_positive", "False Positive"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("affected_devices", models.TextField(blank=True, null=True)),
                ("category_tag", models.CharField(max_length=100)),
                (
                    "framework_mapping",
                    models.TextField(
                        blank=True,
                        help_text="e.g., NIST CSF, CIS Controls, OWASP, ISO 27001",
                        null=True,
                    ),
                ),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("cwe_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "owasp_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerable_components",
                        to="architecture_assessment.securityassessment",
                    ),
                ),
            ],
            options={
                "db_table": "vulnerable_components",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RemediationControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("control_name", models.CharField(max_length=255)),
                ("control_description", models.TextField()),
                ("implementation_details", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("implemented", "Implemented"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "risk_reduction_percentage",
                    models.IntegerField(
                        help_text="Expected percentage reduction in risk",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("verification_notes", models.TextField(blank=True, null=True)),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "evidence_files",
                    models.FileField(
                        blank=True, null=True, upload_to="remediation_evidence/"
                    ),
                ),
                (
                    "vulnerable_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_controls",
                        to="architecture_assessment.vulnerablecomponent",
                    ),
                ),
            ],
            options={
                "db_table": "remediation_controls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "previous_score",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "new_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("change_reason", models.TextField()),
                ("changed_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="architecture_assessment.securityassessment",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_history",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["assessment", "-timestamp"],
                        name="assessment__assessm_c87771_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vulnerablecomponent",
            index=models.Index(
                fields=["assessment", "severity"], name="vulnerable__assessm_bf8848_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerablecomponent",
            index=models.Index(fields=["status"], name="vulnerable__status_722419_idx"),
        ),
        migrations.AddIndex(
            model_name="vulnerablecomponent",
            index=models.Index(
                fields=["category_tag"], name="vulnerable__categor_3ffeac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remediationcontrol",
            index=models.Index(
                fields=["vulnerable_component", "status"],
                name="remediation_vulnera_d00eb3_idx",
            ),
        ),
    ]
