# Generated by Django 5.2.4 on 2026-03-04 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("architecture_assessment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("feedback_count", models.IntegerField(default=0)),
                ("false_positive_count", models.IntegerField(default=0)),
                ("prior_control_count", models.IntegerField(default=0)),
                ("missed_finding_count", models.IntegerField(default=0)),
                (
                    "refined_system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated prompt addendum incorporating all feedback patterns",
                        null=True,
                    ),
                ),
                ("training_summary", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "training_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="remediationcontrol",
            name="evidence_verification_passed",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the AI determined the evidence sufficiently proves implementation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="remediationcontrol",
            name="evidence_verification_result",
            field=models.TextField(
                blank=True,
                help_text="AI analysis result of the uploaded evidence file",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="remediationcontrol",
            name="evidence_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the evidence was last AI-verified",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vulnerablecomponent",
            name="severity_last_calculated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last AI severity recalculation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vulnerablecomponent",
            name="severity_reasoning",
            field=models.TextField(
                blank=True,
                help_text="AI reasoning for the current severity level",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="remediation_evidence/attachments/"),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=50, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("ai_analysis", models.TextField(blank=True, null=True)),
                ("verification_passed", models.BooleanField(blank=True, null=True)),
                (
                    "remediation_control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_attachments",
                        to="architecture_assessment.remediationcontrol",
                    ),
                ),
            ],
            options={
                "db_table": "evidence_files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("false_positive", "False Positive"),
                            ("prior_control", "Prior Control Already Implemented"),
                            ("missed_finding", "Missed Finding"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Explain why this is a false positive, what prior control exists, or describe the missed finding in detail."
                    ),
                ),
                (
                    "false_positive_reason",
                    models.TextField(
                        blank=True,
                        help_text="Specific reason this was a false positive (context, architecture, etc.)",
                        null=True,
                    ),
                ),
                (
                    "prior_control_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prior_control_description", models.TextField(blank=True, null=True)),
                (
                    "prior_control_evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="feedback_evidence/"
                    ),
                ),
                (
                    "missed_finding_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("missed_finding_description", models.TextField(blank=True, null=True)),
                (
                    "missed_finding_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("informational", "Informational"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "missed_finding_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "missed_finding_recommendation",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("incorporated_in_training", models.BooleanField(default=False)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="architecture_assessment.securityassessment",
                    ),
                ),
                (
                    "training_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_items",
                        to="architecture_assessment.trainingjob",
                    ),
                ),
                (
                    "vulnerable_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="architecture_assessment.vulnerablecomponent",
                    ),
                ),
            ],
            options={
                "db_table": "vulnerability_feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["feedback_type", "incorporated_in_training"],
                        name="vulnerabili_feedbac_c71d64_idx",
                    ),
                    models.Index(
                        fields=["assessment"], name="vulnerabili_assessm_f7cb38_idx"
                    ),
                ],
            },
        ),
    ]
