# Generated by Django 5.2.4 on 2026-03-04 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("architecture_assessment", "0002_trainingjob_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remediationcontrol",
            name="evidence_files",
        ),
        migrations.AddField(
            model_name="remediationcontrol",
            name="risk_reduction_reasoning",
            field=models.TextField(
                blank=True,
                help_text="AI reasoning behind the risk_reduction_percentage value",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="remediationcontrol",
            name="risk_reduction_percentage",
            field=models.IntegerField(
                blank=True,
                help_text="AI-calculated percentage reduction in risk. Set automatically; do not supply manually.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
