# Generated by Django 5.2.4 on 2026-03-05 07:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "architecture_assessment",
            "0003_remove_remediationcontrol_evidence_files_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            (
                                "architecture_extraction",
                                "Architecture Diagram Extraction",
                            ),
                            ("risk_score", "Risk Score Calculation"),
                            (
                                "vulnerability_identification",
                                "Vulnerability Identification",
                            ),
                            ("severity_recalculation", "Severity Recalculation"),
                            ("evidence_verification", "Evidence Verification"),
                            ("risk_reduction", "Risk Reduction Calculation"),
                            ("risk_with_controls", "Risk Recalculation With Controls"),
                            (
                                "feedback_training",
                                "Feedback Training / Addendum Generation",
                            ),
                            ("embedding", "Embedding Generation"),
                            ("rag_retrieval", "RAG Context Retrieval"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="e.g. gpt-4o, text-embedding-3-small", max_length=100
                    ),
                ),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Estimated cost in USD based on current OpenAI pricing",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "token_usage",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="securityassessment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this assessment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="chroma_indexed_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of feedback documents indexed into ChromaDB",
            ),
        ),
        migrations.AddField(
            model_name="vulnerabilityfeedback",
            name="chroma_vector_id",
            field=models.CharField(
                blank=True,
                help_text="ChromaDB document ID for this feedback's vector embedding",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="remediationcontrol",
            name="risk_reduction_percentage",
            field=models.IntegerField(
                blank=True,
                help_text="AI-calculated percentage reduction in risk.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityfeedback",
            name="false_positive_reason",
            field=models.TextField(
                blank=True,
                help_text="Specific reason this was a false positive",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="securityassessment",
            index=models.Index(fields=["owner"], name="security_as_owner_i_b72cc9_idx"),
        ),
        migrations.AddIndex(
            model_name="vulnerabilityfeedback",
            index=models.Index(
                fields=["chroma_vector_id"], name="vulnerabili_chroma__0d4b1f_idx"
            ),
        ),
        migrations.AddField(
            model_name="tokenusage",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="token_usage_records",
                to="architecture_assessment.securityassessment",
            ),
        ),
        migrations.AddField(
            model_name="tokenusage",
            name="training_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="token_usage_records",
                to="architecture_assessment.trainingjob",
            ),
        ),
        migrations.AddField(
            model_name="tokenusage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered this AI call (null for background tasks)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="token_usage_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="tokenusage",
            index=models.Index(
                fields=["user", "-created_at"], name="token_usage_user_id_972336_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tokenusage",
            index=models.Index(
                fields=["operation"], name="token_usage_operati_3c3d59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tokenusage",
            index=models.Index(
                fields=["assessment"], name="token_usage_assessm_8d3af2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tokenusage",
            index=models.Index(
                fields=["training_job"], name="token_usage_trainin_93c697_idx"
            ),
        ),
    ]
