# Generated by Django 5.2.4 on 2025-09-29 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EndpointCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.CharField(max_length=255)),
                ("api_id", models.CharField(max_length=255)),
                ("api_name", models.CharField(max_length=255)),
                ("base_url", models.URLField()),
                ("endpoint_type", models.CharField(max_length=50)),
                ("endpoint_url", models.URLField()),
                ("status_code", models.IntegerField()),
                ("response_time", models.FloatField()),
                ("is_accessible", models.BooleanField()),
                ("auth_used", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "endpoint_check_results",
            },
        ),
        migrations.CreateModel(
            name="AdminPanelScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.CharField(max_length=255)),
                ("api_url", models.URLField()),
                ("admin_panel_url", models.URLField()),
                ("is_accessible", models.BooleanField(default=False)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "admin_panel_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("scan_id", "admin_panel_url")},
            },
        ),
        migrations.CreateModel(
            name="APIVersionCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.CharField(max_length=100)),
                ("original_api_url", models.URLField()),
                ("version", models.CharField(max_length=50)),
                ("is_accessible", models.BooleanField()),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "api_version_checks",
                "unique_together": {("scan_id", "original_api_url", "version")},
            },
        ),
        migrations.CreateModel(
            name="DocumentationEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.CharField(db_index=True, max_length=100)),
                ("base_url", models.URLField()),
                ("endpoint_url", models.URLField()),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("swagger", "Swagger/OpenAPI"),
                            ("docs", "Documentation"),
                            ("api-docs", "API Docs"),
                            ("redoc", "ReDoc"),
                            ("openapi", "OpenAPI Spec"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status_code", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success (200)"),
                            ("forbidden", "Forbidden (403)"),
                            ("unauthorized", "Unauthorized (401)"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_content_type", models.CharField(blank=True, max_length=100)),
                ("response_size", models.IntegerField(blank=True, null=True)),
                (
                    "scan_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "response_preview",
                    models.TextField(
                        blank=True, help_text="First 1000 chars of response"
                    ),
                ),
            ],
            options={
                "db_table": "api_9_documentation_endpoint",
                "ordering": ["-scan_timestamp"],
                "unique_together": {("scan_id", "endpoint_url")},
            },
        ),
        migrations.CreateModel(
            name="SubdomainDiscovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.CharField(db_index=True, max_length=100)),
                ("base_url", models.URLField()),
                ("subdomain", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[("live", "Live"), ("dead", "Dead")],
                        default="live",
                        max_length=10,
                    ),
                ),
                (
                    "environment_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("dev", "Development"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("chatgpt_response", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "subdomain_discovery",
                "unique_together": {("scan_id", "subdomain")},
            },
        ),
        migrations.CreateModel(
            name="UnlistedEndpoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.CharField(max_length=100)),
                ("endpoint_url", models.URLField()),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "api_9_unlisted_endpoints",
                "unique_together": {("scan_id", "endpoint_url")},
            },
        ),
        migrations.CreateModel(
            name="VulnerableMethodScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.CharField(db_index=True, max_length=255)),
                ("api_url", models.URLField()),
                ("vulnerable_method", models.CharField(max_length=20)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                (
                    "scan_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vulnerable_method_scans",
                "indexes": [
                    models.Index(
                        fields=["scan_id"], name="vulnerable__scan_id_6d710c_idx"
                    ),
                    models.Index(
                        fields=["vulnerable_method"],
                        name="vulnerable__vulnera_370cfc_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="vulnerable__severit_cdc7ce_idx"
                    ),
                ],
            },
        ),
    ]
