# Generated by Django 5.2.4 on 2025-09-29 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VulnerabilityScanTC1",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scan_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_apis", models.IntegerField(default=0)),
                ("tested_apis", models.IntegerField(default=0)),
                ("vulnerabilities_found", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_6_vulnerability_scan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanStatsTC1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("critical_vulnerabilities", models.IntegerField(default=0)),
                ("high_vulnerabilities", models.IntegerField(default=0)),
                ("medium_vulnerabilities", models.IntegerField(default=0)),
                ("low_vulnerabilities", models.IntegerField(default=0)),
                ("info_vulnerabilities", models.IntegerField(default=0)),
                ("mass_account_tests", models.IntegerField(default=0)),
                ("mass_account_vulnerable", models.IntegerField(default=0)),
                ("total_requests_sent", models.IntegerField(default=0)),
                ("average_response_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "total_execution_time_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("test_success_rate", models.FloatField(blank=True, null=True)),
                ("api_coverage_percentage", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="api_6.vulnerabilityscantc1",
                    ),
                ),
            ],
            options={
                "db_table": "api_6_scan_stats",
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityTestTC1",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_id", models.IntegerField()),
                ("api_name", models.CharField(max_length=255)),
                ("api_url", models.URLField()),
                ("api_method", models.CharField(max_length=10)),
                ("test_type", models.CharField(max_length=100)),
                ("test_name", models.CharField(max_length=255)),
                ("test_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("vulnerable", "Vulnerable"),
                            ("not_vulnerable", "Not Vulnerable"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_vulnerable", models.BooleanField(default=False)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("test_payload", models.JSONField(blank=True, default=dict)),
                ("test_results", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="api_6.vulnerabilityscantc1",
                    ),
                ),
            ],
            options={
                "db_table": "api_6_vulnerability_test",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MassAccountTestResultTC1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_attempts", models.IntegerField(default=0)),
                ("successful_accounts", models.IntegerField(default=0)),
                ("failed_attempts", models.IntegerField(default=0)),
                ("rate_limited_attempts", models.IntegerField(default=0)),
                ("has_email_verification", models.BooleanField(default=False)),
                ("has_phone_verification", models.BooleanField(default=False)),
                ("has_captcha", models.BooleanField(default=False)),
                ("has_rate_limiting", models.BooleanField(default=False)),
                ("has_ip_restrictions", models.BooleanField(default=False)),
                ("average_response_time_ms", models.FloatField(blank=True, null=True)),
                ("success_rate_percentage", models.FloatField(blank=True, null=True)),
                ("accounts_per_minute", models.FloatField(blank=True, null=True)),
                ("generated_accounts", models.JSONField(blank=True, default=list)),
                ("failed_payloads", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mass_account_result",
                        to="api_6.vulnerabilitytesttc1",
                    ),
                ),
            ],
            options={
                "db_table": "api_6_mass_account_test_result",
            },
        ),
        migrations.AddIndex(
            model_name="vulnerabilitytesttc1",
            index=models.Index(
                fields=["scan", "test_type"], name="api_6_vulne_scan_id_0badaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerabilitytesttc1",
            index=models.Index(
                fields=["status", "is_vulnerable"], name="api_6_vulne_status_4b86e7_idx"
            ),
        ),
    ]
