# Generated by Django 5.2.4 on 2025-09-29 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_orch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cloud_metadata", "Cloud Metadata"),
                            ("headers", "Headers"),
                            ("protocols", "Protocols"),
                            ("waf_bypass", "WAF Bypass"),
                            ("encoded", "Encoded Payloads"),
                            ("dns_rebinding", "DNS Rebinding"),
                            ("local_ips", "Local IPs"),
                            ("parameters", "Parameter Payloads"),
                            ("ports", "Port Payloads"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.CharField(max_length=512)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SSRFCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_score", models.IntegerField(default=0)),
                (
                    "risk_factors",
                    models.JSONField(
                        default=list,
                        help_text="List of strings explaining why it's a candidate",
                    ),
                ),
                (
                    "vulnerable_components",
                    models.JSONField(
                        default=dict,
                        help_text="Details of vulnerable parameters/headers found",
                    ),
                ),
                ("identified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_run_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique ID for analysis run",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "heuristic_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When heuristic analysis completed",
                        null=True,
                    ),
                ),
                (
                    "api",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssrf_candidates",
                        to="api_orch.postmanapi",
                    ),
                ),
            ],
            options={
                "verbose_name": "SSRF Candidate",
                "verbose_name_plural": "SSRF Candidates",
                "ordering": ["-risk_score", "identified_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("model_used", models.CharField(max_length=100)),
                ("prompt_sent", models.TextField()),
                ("raw_llm_response", models.TextField()),
                ("analysis_timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_ssrf_candidate", models.BooleanField(default=False)),
                (
                    "primary_payload_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vector_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("recommended_payload", models.JSONField(blank=True, null=True)),
                (
                    "analysis_run_id",
                    models.CharField(
                        blank=True,
                        help_text="Links to same analysis run",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "batch_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Which batch this was processed in",
                        null=True,
                    ),
                ),
                ("parsed_analysis", models.JSONField(blank=True, null=True)),
                (
                    "overall_risk",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("critical_findings_count", models.IntegerField(default=0)),
                (
                    "ssrf_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="api_7.ssrfcandidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SSRFProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload_used",
                    models.TextField(
                        help_text="The specific payload that succeeded in exploitation"
                    ),
                ),
                (
                    "injection_point",
                    models.CharField(
                        help_text="Where the payload was injected (e.g., 'query_param:url', 'header:X-Forwarded-For')",
                        max_length=255,
                    ),
                ),
                (
                    "target_internal_ip_or_domain",
                    models.CharField(
                        help_text="The internal IP or domain targeted (e.g., '169.254.169.254', 'localhost:80')",
                        max_length=255,
                    ),
                ),
                (
                    "proof_details",
                    models.JSONField(
                        blank=True,
                        help_text="Details of the proof (e.g., HTTP status, response content snippet, OOB interaction details)",
                        null=True,
                    ),
                ),
                ("exploitation_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        default="confirmed",
                        help_text="Status of the dynamic proof",
                        max_length=50,
                    ),
                ),
                (
                    "analysis_run_id",
                    models.CharField(
                        blank=True,
                        help_text="Links to same analysis run",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ssrf_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssrf_proofs",
                        to="api_7.ssrfcandidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "SSRF Proof",
                "verbose_name_plural": "SSRF Proofs",
                "ordering": ["-exploitation_timestamp"],
            },
        ),
    ]
