"""
Django settings for AIToolSuite_prod project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from celery.schedules import crontab
from dotenv import load_dotenv
load_dotenv()
# from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ryl-i5*s=s9o$l_=(okg1r^3fbp=kl3zxvl_d4xh!8u#%iz2k%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['api.aitoolsuite.xyz', 'localhost', '127.0.0.1','aitoolsuite.xyz']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_celery_beat',
    'django_celery_results',
    'corsheaders',

    'login',
    'homepage',
    'scanner',
    'scanner_results',
    'connector',
    'api_orch',
    'api_custom_testing',
    'api_2',
    'api_4',
    'api_6',
    'api_7',
    'api_8',
    'api_9',
    'threat_model',
    'architecture_assessment'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://localhost:5173',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:5173',  
    'https://aitoolsuite.xyz',
    'https://api.aitoolsuite.xyz',
    'http://192.168.10.19.sslip.io:3000',
    'http://172.20.10.2.sslip.io:3000',
]

CORS_ALLOW_HEADERS = [
    'X-Requested-With',
    'Content-Type',
    'authorization',
]

ROOT_URLCONF = 'AIToolSuite_prod.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AIToolSuite_prod.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'AIToolSuite',
        'USER': 'postgres',
        'PASSWORD': 'Qwerty@050725',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # If you store shared static files in the root directory
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default authentication backend
)

AUTH_USER_MODEL = 'auth.User'

LOGIN_URL = '/login/'

#Media files configuration (for Postman collection uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 40 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 40 * 1024 * 1024  # 10MB

# ChromaDB Configuration
CHROMADB_PATH = os.path.join(BASE_DIR, 'chroma_db')

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=2),  # Update to 2 minutes in production
    "REFRESH_TOKEN_LIFETIME": timedelta(days=3),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "SIGNING_KEY": os.getenv("JWT_SECRET_KEY"),  # Use `os.getenv("SECRET_KEY")` in production
    "AUTH_HEADER_TYPES": ("Bearer",),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_RENDERER_CLASSES': (  
        'rest_framework.renderers.JSONRenderer',  
        "rest_framework_csv.renderers.CSVRenderer",
        'rest_framework.renderers.BrowsableAPIRenderer',  # Enables DRF web UI  
    ),

    'DEFAULT_FILTER_BACKENDS': ( 
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_PAGINATION_CLASS': 'api_4.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,

    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/hour',
        'user': '1000/hour'
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },

    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/runtime_logs.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'api6_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/api6_vulnerability_tests.log',
            'formatter': 'verbose',
        },
        'risk_assessment_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/risk_assessment.log',
            'formatter': 'verbose',
        },
    },

    'loggers': {
        'scanner': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },

        'api_custom_testing': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },

        'api_9': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'api_9.views': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'api_9.services': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'api_9.tasks': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },

        'api_4': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'api_4.views': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'api_4.utils': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },

        'api_8': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },

        'api_2': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },

        'api_6': {
            'handlers': ['api6_file'],
            'level': 'INFO',
            'propagate': True,
        },

        'architecture_assessment': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# For Redis
#CELERY_BROKER_URL = 'redis://localhost:6379/0'
#CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# For RabbitMQ
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_RESULT_EXTENDED = True

# Task result settings
CELERY_RESULT_EXPIRES = 3600
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_SEND_EVENTS = True
CELERY_RESULT_PERSISTENT = True

# Celery settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BEAT_SCHEDULE = {
    'refresh-scan-tokens': {
        'task': 'api_orch.tasks.refresh_scan_tokens',
        'schedule': crontab(minute='*/10'),  # Run every 10 minutes
    },
    'cleanup-old-scans': {
        'task': 'api_8.tasks.cleanup_old_scans_tc2',
        'schedule': 86400.0,  # Run daily
    },
    'update-vulnerability-intelligence': {
        'task': 'api_8.tasks.update_vulnerability_intelligence_tc2',
        'schedule': 604800.0,  # Run weekly
    },
    'cleanup-old-scans-tc3': {
        'task': 'api_8.tasks.cleanup_old_scans_tc2',
        'schedule': crontab(hour=2, minute=0),  # Run daily at 2 AM
    },
    'weekly-security-training': {
        'task': 'architecture_assessment.tasks.run_weekly_training',
        'schedule': crontab(hour=2, minute=0, day_of_week=1),  # Every Monday 02:00 UTC
    },
}
CELERYD_FORCE_EXECV = True

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # If using HTTPS
USE_X_FORWARDED_HOST = True

# Security Headers for API responses
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# hCaptcha Configuration
HCAPTCHA_SITE_KEY = os.environ.get('HCAPTCHA_SITE_KEY')
HCAPTCHA_SECRET_KEY = os.environ.get('HCAPTCHA_SECRET_KEY')

# OpenAI API Configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY") # Replace with os.getenv("OPENAI_API_KEY") in production
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o')
OPENAI_RATE_LIMIT = {
    'requests_per_minute': 60,
    'tokens_per_minute': 50000,
}

# API-4 TC-3 File upload scanner specific settings
FILE_UPLOAD_SCANNER = {
    'MAX_FILE_SIZE': 100 * 1024 * 1024,  # 100MB max test file size
    'REQUEST_TIMEOUT': 300,  # 5 minutes timeout for requests
    'MAX_CONCURRENT_SCANS': 3,  # Maximum concurrent scans
    'WEBSHELL_PATTERNS': [
        '<?php',
        '<%@',
        'System.Diagnostics.Process',
        'Runtime.getRuntime().exec',
        'eval(',
        'exec(',
        'passthru(',
        'shell_exec(',
    ],
    'DANGEROUS_EXTENSIONS': [
        '.php', '.jsp', '.aspx', '.asp', '.pl', '.py', '.rb',
        '.exe', '.bat', '.cmd', '.sh', '.ps1', '.vbs'
    ],
    'SAFE_EXTENSIONS': [
        '.jpg', '.jpeg', '.png', '.gif', '.bmp', '.svg',
        '.pdf', '.doc', '.docx', '.txt', '.csv'
    ]
}

# API-4 TC-5 File Download Count & Vulnerability Threshold settings
FILE_DOWNLOAD_TEST_COUNT = 10
VULNERABILITY_THRESHOLD = 0.7

# Security settings for API requests
REQUESTS_TIMEOUT = 30
MAX_API_RETRIES = 3

# API-8 TC-1 CORS Misconfiguration Scanner specific settings
CORS_SCANNER_SETTINGS = {
    'REQUEST_TIMEOUT': 10,  # seconds
    'MAX_CONCURRENT_SCANS': 5,
    'TEST_ORIGINS': [
        'https://evil.example',
        'https://malicious.com',
        'http://127.0.0.1:8080',
        'null'
    ],
    'VULNERABILITY_THRESHOLDS': {
        'CRITICAL': 9.0,
        'HIGH': 7.0,
        'MEDIUM': 4.0,
        'LOW': 2.0,
    }
}

# API-8 TC-2 TLS Scanner Configuration
API_8_CONFIG = {
    'MAX_CONCURRENT_SCANS': 5,
    'SCAN_TIMEOUT_SECONDS': 3600,  # 1 hour max per scan
    'API_TIMEOUT_SECONDS': 30,     # 30 seconds per API test
    'ENABLE_AI_ANALYSIS': True,
    'TESTSSL_PATH': '/usr/local/bin/testssl.sh',  # Path to testssl.sh
    'REPORT_RETENTION_DAYS': 180,  # Keep reports for 6 months
}

# API-8 TC-3 Excessive Debug Information Scanner Configurations
VULNERABILITY_SCANNER_CONFIG = {
    'max_concurrent_scans': 5,
    'request_timeout': 30,  # seconds
    'max_payload_size': 10 * 1024 * 1024,  # 1MB
    'enable_ai_analysis': True,
    'enable_external_tools': True,  # Set to False if you don't have nikto, dirb etc installed
    'rate_limit_delay': 1,  # seconds between requests to same host
    'user_agent': 'VulnerabilityScanner-TC2/1.0',
    'max_redirects': 5,
}

# API-2 TC-1 Missing/Weak Authentication on Sensitive Endpoints Configurations
API2_SETTINGS = {
    'SCAN_TIMEOUT': 300,  # 5 minutes timeout for individual API scans
    'MAX_CONCURRENT_SCANS': 5,
    'REQUEST_TIMEOUT': 10,  # Timeout for individual HTTP requests
    'MAX_RESPONSE_SIZE': 1000,  # Limit response body size to store
    'ENABLE_REAL_HTTP_REQUESTS': True,  # Set to False to disable actual HTTP requests during testing
}

# API-2 TC-2 Unrestricted Credential Stuffing
SCAN_SETTINGS = {
    'MAX_CONCURRENT_SCANS': 5,
    'MAX_ATTEMPTS_PER_API': 50,
    'REQUEST_TIMEOUT': 30,
    'DELAY_BETWEEN_REQUESTS': 0.1,  # seconds
    'MAX_RESPONSE_SAMPLES': 5,
    'ENABLE_AI_ANALYSIS': True,
    'SCAN_THREAD_POOL_SIZE': 5,
}

# API-2 TC-3 Weak Password Policy
VULNERABILITY_SCAN_TIMEOUT = 300  # 5 minutes
MAX_CONCURRENT_SCANS = 5
SCAN_RESULT_RETENTION_DAYS = 90
SECURITY_TEST_RATE_LIMIT = {
    'requests_per_minute': 10,
    'burst_size': 20
}
CLI_TOOLS = {
    'nmap': {
        'enabled': True,
        'timeout': 300,
        'default_args': ['-sV', '--script=vuln']
    },
    'sqlmap': {
        'enabled': True,
        'timeout': 600,
        'default_args': ['--batch', '--level=3', '--risk=2']
    },
    'nikto': {
        'enabled': True,
        'timeout': 900
    }
}

# API-2 TC-4 JWT Forgery/None Algorithm Exploit
JWT_SCANNER_CONFIG = {
    'REQUEST_TIMEOUT': 30,  # seconds
    'MAX_RETRIES': 3,
    'MAX_RESPONSE_SIZE': 1000,  # characters to store in DB
    'CONCURRENT_SCANS': 1,  # Number of concurrent scans allowed
    'DEFAULT_WEAK_SECRETS': [
        'secret', 'password', '123456', 'admin', 'test', 'key',
        'jwt', 'token', 'your-256-bit-secret', 'supersecret'
    ],
    'DEFAULT_ROLE_PAYLOADS': [
        {'role': 'admin'},
        {'role': 'administrator'},
        {'is_admin': True},
        {'admin': True},
        {'user_type': 'admin'},
        {'permissions': ['admin']},
        {'level': 'admin'},
        {'privilege': 'admin'}
    ]
}

# API-2 TC-5 Insecure Password Reset Flow
SECURITY_SCANNER_CONFIG = {
    'MAX_CONCURRENT_REQUESTS': 5,
    'REQUEST_TIMEOUT': 30,  # seconds
    'RETRY_ATTEMPTS': 3,
    'DELAY_BETWEEN_REQUESTS': 1.0,  # seconds
    'MAX_RESPONSE_SIZE': 1024 * 1024,  # 1MB
    'USER_AGENT': 'SecurityScanner/1.0',
}
API_SECURITY_CONFIG = {
    'ENABLE_AI_ANALYSIS': True,
    'AI_CONFIDENCE_THRESHOLD': 0.7,
    'RISK_SCORE_THRESHOLD': 5.0,
    'AUTO_VERIFY_HIGH_CONFIDENCE': True,
    'SAVE_REQUEST_RESPONSES': True,
    'MAX_SCAN_DURATION': 3600,  # 1 hour
}

# API-6 TC-1 Mass Account Creation
API_6_SETTINGS = {
    'DEFAULT_SCAN_TIMEOUT': 1800,  # 30 minutes
    'MAX_ACCOUNTS_PER_API': 10,
    'DEFAULT_REQUEST_TIMEOUT': 30,
    'INTERACTSH_DOMAIN': 'interact.sh',
    'OOB_TIMEOUT': 60,  # seconds to wait for OOB callbacks
    'ENABLE_AI_PAYLOADS': True,  # Enable AI-generated payloads
    'MAX_PAYLOAD_SIZE': 10000,  # Maximum size for payloads
    'RATE_LIMIT_DELAY': 0.5,  # Delay between requests in seconds
}
ASYNC_TIMEOUT = 300  # 5 minutes default timeout for scans
MAX_CONCURRENT_TESTS = 10  # Maximum concurrent vulnerability tests

# ARCHITECTURE ASSESSMENT - Create necessary directories
os.makedirs(MEDIA_ROOT, exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'architecture_diagrams'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'architecture_files'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'remediation_evidence'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'reports'), exist_ok=True)
os.makedirs(CHROMADB_PATH, exist_ok=True)